server:
  port: 8083

spring:
  application:
    name: match-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}

services:
  auth-url: ${AUTH_SERVICE_URL:http://localhost:8081}
  challenge-url: ${CHALLENGE_SERVICE_URL:http://localhost:8082}
  leaderboard-url: ${LEADERBOARD_SERVICE_URL:http://localhost:8084}
